name: "Cache"
on:
  pull_request:
  push:
    branches:
      - "main"

concurrency:
  group: ${{ github.ref }}-cache
  cancel-in-progress: true

jobs:
  # idea credit: https://github.com/nix-community/nix-github-actions/blob/bfeb681177b5128d061ebbef7ded30bc21a3f135/.github/workflows/detsys-nix-installer-action.yml
  matrix:
    name: Calculate recent-versions matrix
    runs-on: ubuntu-latest
    outputs:
      calculated: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v5
      - uses: cachix/install-nix-action@v31
      - name: Set Matrix
        id: set-matrix
        run: |
          set -eux -o pipefail
          echo "matrix=$(nix eval --json '.#lib.recentMatrix')" >> "$GITHUB_OUTPUT"

  packages:
    name: Cache ${{ matrix.elixir }} on OTP ${{ matrix.erlang }} (${{ matrix.os }})
    needs: matrix
    runs-on: ${{ matrix.os }}
    strategy:
      matrix: ${{ fromJSON(needs.matrix.outputs.calculated) }}
    steps:
      - uses: actions/checkout@v5
      - uses: cachix/install-nix-action@v31
        with:
          extra_nix_config: |
            extra-substituters = https://nix-beam-flakes.cachix.org
            extra-trusted-public-keys = nix-beam-flakes.cachix.org-1:iRMzLmb/dZFw7v08Rp3waYlWqYZ8nR3fmtFwq2prdk4=
            accept-flake-config = true

      - uses: cachix/cachix-action@v16
        if: github.ref == 'refs/heads/main'
        with:
          name: nix-beam-flakes
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
          pathsToPush: "./result"
          useDaemon: false
          cachixArgs: --verbose

      - run: |
          printf \
            "elixir %s\nerlang %s" \
              ${{ matrix.elixir }} \
              ${{ matrix.erlang }} \
            | tee ./dev/example/.tool-versions
      - run: nix -L build .#example
